name: t3dd25/extbase-plugin
typeName: t3dd25_extbaseplugin
group: t3dd25
prefixFields: true
prefixType: vendor
basics:
  - TYPO3/Appearance
  - TYPO3/Links
fields:
  -
    identifier: header
    useExistingField: true
