name: t3dd25/record3-list
typeName: t3dd25_record3list
group: t3dd25
prefixFields: true
prefixType: vendor
basics:
  - TYPO3/Appearance
  - TYPO3/Links
fields:
  -
    identifier: header
    useExistingField: true
