name: example/text
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
  - identifier: bodytext
    useExistingField: true
    enableRichtext: true
  -
    identifier: T3DD25/Links
    type: Basic
  -
    identifier: fieldtype_image
    type: Image
    label: New Image FieldType
  - identifier: modified_field
    type: Textarea
    label: Modified Text Field
